import { useVisionCanvas } from '../VisionCanvasContext';

export function useVisionTools() {
  const {
    tool,
    setTool,
    toolRef,
    hoverId,
    setHoverId,
    clearHideTimer,
    scheduleHide,
    marqueeRect,
    marqueeRef,
    handleBackgroundPointerDown,
    drawBoxPreview,
    beginDraw,
    activeResize,
    handleBboxResizePointerDown,
    handleBboxResizePointerMove,
    handleBboxResizePointerUp,
    dragRef,
    shiftToggledRef,
    beginDrag,
    handleMediaPointerMove,
    handleMediaPointerUp,
    multiHighlightInput,
    setMultiHighlightInput,
    highlightInputs,
    setHighlightInputs,
  } = useVisionCanvas();
  return {
    tool,
    setTool,
    toolRef,
    hoverId,
    setHoverId,
    clearHideTimer,
    scheduleHide,
    marqueeRect,
    marqueeRef,
    handleBackgroundPointerDown,
    drawBoxPreview,
    beginDraw,
    activeResize,
    handleBboxResizePointerDown,
    handleBboxResizePointerMove,
    handleBboxResizePointerUp,
    dragRef,
    shiftToggledRef,
    beginDrag,
    handleMediaPointerMove,
    handleMediaPointerUp,
    multiHighlightInput,
    setMultiHighlightInput,
    highlightInputs,
    setHighlightInputs,
  };
}
