import { useVisionCanvas } from '../VisionCanvasContext';

export function useVisionSegmentation() {
  const {
    segments,
    setSegments,
    segmentsRef,
    selectedMask,
    setSelectedMask,
    hoveredMask,
    soloTag,
    setSoloTag,
    pendingBoxLabel,
    setPendingBoxLabel,
    userBoxes,
    setUserBoxes,
    handleMaskSelect,
    handleMaskHover,
    clearSegment,
    replaceReadyTag,
    deleteMask,
    deleteAllMasksForTag,
    removeSegmentTag,
    submitSegment,
    confirmPendingBoxLabel,
    cancelPendingBoxLabel,
  } = useVisionCanvas();
  return {
    segments,
    setSegments,
    segmentsRef,
    selectedMask,
    setSelectedMask,
    hoveredMask,
    soloTag,
    setSoloTag,
    pendingBoxLabel,
    setPendingBoxLabel,
    userBoxes,
    setUserBoxes,
    handleMaskSelect,
    handleMaskHover,
    clearSegment,
    replaceReadyTag,
    deleteMask,
    deleteAllMasksForTag,
    removeSegmentTag,
    submitSegment,
    confirmPendingBoxLabel,
    cancelPendingBoxLabel,
  };
}
